<?php
declare(strict_types=1);

// MagicTheGatheringTwo SDK configuration

class MagicTheGatheringTwoConfig
{
    public static function make_config(): array
    {
        return [
            "main" => [
                "name" => "MagicTheGatheringTwo",
            ],
            "feature" => [
                "test" => [
          'options' => [
            'active' => false,
          ],
        ],
            ],
            "options" => [
                "base" => "https://api.magicthegathering.io/v1",
                "auth" => [
                    "prefix" => "Bearer",
                ],
                "headers" => [
          'content-type' => 'application/json',
        ],
                "entity" => [
                    "card" => [],
                    "format" => [],
                    "set" => [],
                    "set_booster" => [],
                    "subtype" => [],
                    "supertype" => [],
                    "type" => [],
                ],
            ],
            "entity" => [
        'card' => [
          'fields' => [
            [
              'name' => 'artist',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 0,
            ],
            [
              'name' => 'border',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 1,
            ],
            [
              'name' => 'card',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 2,
            ],
            [
              'name' => 'cmc',
              'req' => false,
              'type' => '`$NUMBER`',
              'active' => true,
              'index$' => 3,
            ],
            [
              'name' => 'color',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 4,
            ],
            [
              'name' => 'color_identity',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 5,
            ],
            [
              'name' => 'flavor',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 6,
            ],
            [
              'name' => 'foreign_name',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 7,
            ],
            [
              'name' => 'hand',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 8,
            ],
            [
              'name' => 'id',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 9,
            ],
            [
              'name' => 'image_url',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 10,
            ],
            [
              'name' => 'layout',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 11,
            ],
            [
              'name' => 'legality',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 12,
            ],
            [
              'name' => 'life',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 13,
            ],
            [
              'name' => 'loyalty',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 14,
            ],
            [
              'name' => 'mana_cost',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 15,
            ],
            [
              'name' => 'multiverseid',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 16,
            ],
            [
              'name' => 'name',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 17,
            ],
            [
              'name' => 'number',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 18,
            ],
            [
              'name' => 'original_text',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 19,
            ],
            [
              'name' => 'original_type',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 20,
            ],
            [
              'name' => 'power',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 21,
            ],
            [
              'name' => 'printing',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 22,
            ],
            [
              'name' => 'rarity',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 23,
            ],
            [
              'name' => 'release_date',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 24,
            ],
            [
              'name' => 'reserved',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 25,
            ],
            [
              'name' => 'ruling',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 26,
            ],
            [
              'name' => 'set',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 27,
            ],
            [
              'name' => 'set_name',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 28,
            ],
            [
              'name' => 'source',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 29,
            ],
            [
              'name' => 'starter',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 30,
            ],
            [
              'name' => 'subtype',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 31,
            ],
            [
              'name' => 'supertype',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 32,
            ],
            [
              'name' => 'text',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 33,
            ],
            [
              'name' => 'timeshifted',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 34,
            ],
            [
              'name' => 'toughness',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 35,
            ],
            [
              'name' => 'type',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 36,
            ],
            [
              'name' => 'variation',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 37,
            ],
            [
              'name' => 'watermark',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 38,
            ],
          ],
          'name' => 'card',
          'op' => [
            'list' => [
              'name' => 'list',
              'points' => [
                [
                  'args' => [
                    'query' => [
                      [
                        'kind' => 'query',
                        'name' => 'artist',
                        'orig' => 'artist',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'cmc',
                        'orig' => 'cmc',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'color',
                        'orig' => 'color',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'color_identity',
                        'orig' => 'color_identity',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'contain',
                        'orig' => 'contain',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'flavor',
                        'orig' => 'flavor',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'game_format',
                        'orig' => 'game_format',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'id',
                        'orig' => 'id',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'language',
                        'orig' => 'language',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'layout',
                        'orig' => 'layout',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'legality',
                        'orig' => 'legality',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'loyalty',
                        'orig' => 'loyalty',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'multiverseid',
                        'orig' => 'multiverseid',
                        'reqd' => false,
                        'type' => '`$INTEGER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'name',
                        'orig' => 'name',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'number',
                        'orig' => 'number',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'order_by',
                        'orig' => 'order_by',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'example' => 1,
                        'kind' => 'query',
                        'name' => 'page',
                        'orig' => 'page',
                        'reqd' => false,
                        'type' => '`$INTEGER`',
                        'active' => true,
                      ],
                      [
                        'example' => 100,
                        'kind' => 'query',
                        'name' => 'page_size',
                        'orig' => 'page_size',
                        'reqd' => false,
                        'type' => '`$INTEGER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'power',
                        'orig' => 'power',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'random',
                        'orig' => 'random',
                        'reqd' => false,
                        'type' => '`$BOOLEAN`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'rarity',
                        'orig' => 'rarity',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'set',
                        'orig' => 'set',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'set_name',
                        'orig' => 'set_name',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'subtype',
                        'orig' => 'subtype',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'supertype',
                        'orig' => 'supertype',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'text',
                        'orig' => 'text',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'toughness',
                        'orig' => 'toughness',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'type',
                        'orig' => 'type',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'type',
                        'orig' => 'type',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                  ],
                  'method' => 'GET',
                  'orig' => '/cards',
                  'parts' => [
                    'cards',
                  ],
                  'select' => [
                    'exist' => [
                      'artist',
                      'cmc',
                      'color',
                      'color_identity',
                      'contain',
                      'flavor',
                      'game_format',
                      'id',
                      'language',
                      'layout',
                      'legality',
                      'loyalty',
                      'multiverseid',
                      'name',
                      'number',
                      'order_by',
                      'page',
                      'page_size',
                      'power',
                      'random',
                      'rarity',
                      'set',
                      'set_name',
                      'subtype',
                      'supertype',
                      'text',
                      'toughness',
                      'type',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'list',
            ],
            'load' => [
              'name' => 'load',
              'points' => [
                [
                  'args' => [
                    'params' => [
                      [
                        'kind' => 'param',
                        'name' => 'id',
                        'orig' => 'id',
                        'reqd' => true,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                  ],
                  'method' => 'GET',
                  'orig' => '/cards/{id}',
                  'parts' => [
                    'cards',
                    '{id}',
                  ],
                  'select' => [
                    'exist' => [
                      'id',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'load',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'format' => [
          'fields' => [
            [
              'name' => 'format',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 0,
            ],
          ],
          'name' => 'format',
          'op' => [
            'list' => [
              'name' => 'list',
              'points' => [
                [
                  'method' => 'GET',
                  'orig' => '/formats',
                  'parts' => [
                    'formats',
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'args' => [],
                  'select' => [],
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'set' => [
          'fields' => [
            [
              'name' => 'block',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 0,
            ],
            [
              'name' => 'booster',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 1,
            ],
            [
              'name' => 'border',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 2,
            ],
            [
              'name' => 'code',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 3,
            ],
            [
              'name' => 'gatherer_code',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 4,
            ],
            [
              'name' => 'magic_cards_info_code',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 5,
            ],
            [
              'name' => 'mkm_id',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 6,
            ],
            [
              'name' => 'mkm_name',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 7,
            ],
            [
              'name' => 'name',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 8,
            ],
            [
              'name' => 'online_only',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 9,
            ],
            [
              'name' => 'release_date',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 10,
            ],
            [
              'name' => 'set',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 11,
            ],
            [
              'name' => 'type',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 12,
            ],
          ],
          'name' => 'set',
          'op' => [
            'list' => [
              'name' => 'list',
              'points' => [
                [
                  'args' => [
                    'query' => [
                      [
                        'kind' => 'query',
                        'name' => 'block',
                        'orig' => 'block',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'name',
                        'orig' => 'name',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                  ],
                  'method' => 'GET',
                  'orig' => '/sets',
                  'parts' => [
                    'sets',
                  ],
                  'select' => [
                    'exist' => [
                      'block',
                      'name',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'list',
            ],
            'load' => [
              'name' => 'load',
              'points' => [
                [
                  'args' => [
                    'params' => [
                      [
                        'kind' => 'param',
                        'name' => 'id',
                        'orig' => 'id',
                        'reqd' => true,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                  ],
                  'method' => 'GET',
                  'orig' => '/sets/{id}',
                  'parts' => [
                    'sets',
                    '{id}',
                  ],
                  'select' => [
                    'exist' => [
                      'id',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'load',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'set_booster' => [
          'fields' => [
            [
              'name' => 'artist',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 0,
            ],
            [
              'name' => 'border',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 1,
            ],
            [
              'name' => 'cmc',
              'req' => false,
              'type' => '`$NUMBER`',
              'active' => true,
              'index$' => 2,
            ],
            [
              'name' => 'color',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 3,
            ],
            [
              'name' => 'color_identity',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 4,
            ],
            [
              'name' => 'flavor',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 5,
            ],
            [
              'name' => 'foreign_name',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 6,
            ],
            [
              'name' => 'hand',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 7,
            ],
            [
              'name' => 'id',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 8,
            ],
            [
              'name' => 'image_url',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 9,
            ],
            [
              'name' => 'layout',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 10,
            ],
            [
              'name' => 'legality',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 11,
            ],
            [
              'name' => 'life',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 12,
            ],
            [
              'name' => 'loyalty',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 13,
            ],
            [
              'name' => 'mana_cost',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 14,
            ],
            [
              'name' => 'multiverseid',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 15,
            ],
            [
              'name' => 'name',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 16,
            ],
            [
              'name' => 'number',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 17,
            ],
            [
              'name' => 'original_text',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 18,
            ],
            [
              'name' => 'original_type',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 19,
            ],
            [
              'name' => 'power',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 20,
            ],
            [
              'name' => 'printing',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 21,
            ],
            [
              'name' => 'rarity',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 22,
            ],
            [
              'name' => 'release_date',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 23,
            ],
            [
              'name' => 'reserved',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 24,
            ],
            [
              'name' => 'ruling',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 25,
            ],
            [
              'name' => 'set',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 26,
            ],
            [
              'name' => 'set_name',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 27,
            ],
            [
              'name' => 'source',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 28,
            ],
            [
              'name' => 'starter',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 29,
            ],
            [
              'name' => 'subtype',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 30,
            ],
            [
              'name' => 'supertype',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 31,
            ],
            [
              'name' => 'text',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 32,
            ],
            [
              'name' => 'timeshifted',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 33,
            ],
            [
              'name' => 'toughness',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 34,
            ],
            [
              'name' => 'type',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 35,
            ],
            [
              'name' => 'variation',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 36,
            ],
            [
              'name' => 'watermark',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 37,
            ],
          ],
          'name' => 'set_booster',
          'op' => [
            'list' => [
              'name' => 'list',
              'points' => [
                [
                  'args' => [
                    'params' => [
                      [
                        'kind' => 'param',
                        'name' => 'id',
                        'orig' => 'id',
                        'reqd' => true,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                  ],
                  'method' => 'GET',
                  'orig' => '/sets/{id}/booster',
                  'parts' => [
                    'sets',
                    '{id}',
                    'booster',
                  ],
                  'select' => [
                    'exist' => [
                      'id',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'subtype' => [
          'fields' => [
            [
              'name' => 'subtype',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 0,
            ],
          ],
          'name' => 'subtype',
          'op' => [
            'list' => [
              'name' => 'list',
              'points' => [
                [
                  'method' => 'GET',
                  'orig' => '/subtypes',
                  'parts' => [
                    'subtypes',
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'args' => [],
                  'select' => [],
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'supertype' => [
          'fields' => [
            [
              'name' => 'supertype',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 0,
            ],
          ],
          'name' => 'supertype',
          'op' => [
            'list' => [
              'name' => 'list',
              'points' => [
                [
                  'method' => 'GET',
                  'orig' => '/supertypes',
                  'parts' => [
                    'supertypes',
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'args' => [],
                  'select' => [],
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'type' => [
          'fields' => [
            [
              'name' => 'type',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 0,
            ],
          ],
          'name' => 'type',
          'op' => [
            'list' => [
              'name' => 'list',
              'points' => [
                [
                  'method' => 'GET',
                  'orig' => '/types',
                  'parts' => [
                    'types',
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'args' => [],
                  'select' => [],
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
      ],
        ];
    }


    public static function make_feature(string $name)
    {
        require_once __DIR__ . '/features.php';
        return MagicTheGatheringTwoFeatures::make_feature($name);
    }
}
